name: Demo workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Demo create file
        run: touch name.txt
      - name: Add line to file
        run: echo dwqdwqdqw > name.txt
      - name: Cat file
        run: cat name.txt
